title: The Financial Clone
description: AI-Curated Market News
url: "https://mlegkovskis.github.io"
baseurl: "/gpFT"
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
exclude:
  - scripts/
  - requirements.txt
  - README.md
  - headlines.json
